<a href="https://colab.research.google.com/github/lshpy/python_basic/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 모듈과 패키지


In [ ]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
# 패키지는 여러 모듈을 담은 것

# import 모듈
# 모듈. 변수
# 모듈.함수()
# 모듈. 클래스()


In [ ]:
import torch

In [ ]:
import math

print(math.pi)
# print(pi) # 모듈 안의 변수이기 때문에 그냥은 없음

3.141592653589793


In [ ]:
import math as m # 모듈의 이름을 간소화하자

print(m.pi)

3.141592653589793


In [ ]:
from math import pi, sqrt

print(pi)
print(sqrt(4))
# 여기서는 그냥 함수이름만 가지고도 사용 가능

3.141592653589793
2.0


In [ ]:
from math import * # 다가지고 와


print(pi)
print(sin(pi))

3.141592653589793
1.2246467991473532e-16


In [ ]:
from math import sqrt as s
print(s(9))

3.0


In [ ]:
from math import sqrt as s,  pi as p # 2개도 가능
print(p)
print(s(9))


3.141592653589793
3.0


In [ ]:
#import 패키지
#imprt 패키지, 모듈
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지. 모듈. 클래스()


In [ ]:
import numpy as np # numpy는 라이브러리
#numerical python

a= np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy.random # random 모듈도 가지고 온다
print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3열 3행을 의미한다

# 샘플의 형을 의미


[[-1.04114078  0.23595827 -0.19869618]
 [ 1.36616334  1.47703448  0.37270594]
 [ 2.4004536  -0.04897934 -0.48272539]]


In [ ]:
import numpy.random as nr
print(nr.randn(3,3))

[[ 1.00940834 -0.5243892   0.92750076]
 [ 1.4629787   0.42263357 -1.79017867]
 [-0.87192793  0.25414885 -1.17242147]]


In [ ]:
from numpy.random import randn
print(randn(3,3))

[[-1.32401177 -0.67299002  0.44206557]
 [ 1.45640382  1.03097568  1.25777086]
 [ 0.6041652   1.59584462  1.29655405]]


In [ ]:
from numpy.random import *
print(randn(3,3))
print(rand(3,3)) # uniform distribution(0~1) 사이의 값

[[-0.27521    -0.93453568 -1.07224392]
 [ 0.29976683 -1.1867898  -0.6102095 ]
 [ 0.38349846  0.04185497 -0.36540054]]
[[0.2418446  0.23001296 0.75881387]
 [0.44044606 0.08365576 0.29585562]
 [0.8465672  0.29232661 0.06360046]]


In [ ]:
from numpy.random import  randn as rn, rand as r
print(rn(3,3))
print(r(3,3))


[[-0.36776815  0.07165988  1.95391856]
 [ 1.26385072 -0.82824852  0.2995992 ]
 [-0.06027391 -0.75497446  1.12896467]]
[[0.59035955 0.30552729 0.77868157]
 [0.202341   0.30915759 0.32550981]
 [0.5271919  0.72396258 0.16297446]]


# numpy 본격적으로

In [ ]:
import numpy as np
a = np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a) # 리스트를 리스트로
print(type(a))
print(a.dtype) # dara type
print(a.shape) # 숫자 4개니까 4차원
print(a[0])
b = np.array([1,2,3.1,4])
print(b.dtype) # float
print(b.shape)
print(b[0]) #  int 여도 하나가 float이면 float로 바뀌어서 출력 1--> 1.0으로


[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
1
float64
(4,)
1.0


In [ ]:
a=np.array(1234567478937498274329482093840948390842840937)
print(a)
print(a.dtype) # 64이상이 되면 메몰 초과로 object 출력

1234567478937498274329482093840948390842840937
object


In [ ]:
import numpy as np
A = np.array([[1,2], [3,4]]) # 리스트 속의 리스트
print(A)
print(A.shape) # 2행 2열 (2,2)
print(A.ndim) # 2 , #차원의 수
print(A.size) # A.shape 의 모든 수를 곱한 값 : 2*2 = 4


[[1 2]
 [3 4]]
(2, 2)
2
4


In [ ]:
print(np.zeros(5))
print(np.zeros_like(A)) # A의 크기에 맞추어서 0을 채워준다
print(np.ones_like(A))

print(np.zeros((3,3))) # 반드시 하나의 값만! 리스트나 튜플로 묶어주기

import torch
print(torch.zeros((3,3)))
print(np.arange(3,10,2)) #3부터 10까지 2 간격으로 출력한다 # range--> array

print(type(np.arange(3,10,2) )) # 소수점 가능

print(np.arange(0,1,0.1))  # 소수점 가능
print(np.linspace(0, 1, 10, endpoint = False)) # 0에서부터 1포함 10개로, 단 끝지점은 포함하지 않는다
# endpoint 를 초함하는 것이 default다

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
[3 5 7 9]
<class 'numpy.ndarray'>
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
# boolan 인덱싱
import numpy as np
a=[1,2,3,4,5,3,3]
print(a==3)

b = np.array([1,2,3,4,3,2,3,2,3])
print(b==3)
print(b[b==3]) # b==3임을 만족하는 행렬에서 true 만 뽑아서 다시 정렬
b[b==3] = 100 # 3인 true 부분을 100으로 치환해서 리스트에 집어넣을 수도 있음
print(b)



A = np.array([[1,2], [3,4], [5,6], [7,8]])

B = np.array([True, False,False, True])

A[B,:] #0 행행, 3행행 슬라이싱 # True 의 위치에 따라 슬라이싱

b= np.array([1,2,3,4])
print(b)
print(b[[True, True, False, False]]) # 0행, 1행 슬라이싱


False
[False False  True False  True False  True False  True]
[3 3 3 3]
[  1   2 100   4 100   2 100   2 100]
[1 2 3 4]
[1 2]


In [ ]:
# 3차원 행렬 인덱싱

A= np.array([[[0,1,2,3], [4,5,6,7], [8,9,10,11]],
             [[12,13,14,15], [16,17,18,19], [20,21,22,23]]])

print(A)

print(A.shape) # (2,3,4)
# 3차원 안 2개, 각 리스트 안에 3개 그리고 제일 작은 리스트 안에 4개
# 차원 내림차순으로 개수 세면서 튜플로 완성

print(A[0,1,2]) # 0번째 1번쨰 2번째



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


# numpy 의 여러 함수들

In [ ]:
A= np.random.randn(3,3) # 정규분포
B = np.random.rand(3,3) # 0과 1 사이의 균등분포
print(A)
print(B)
print(A[:,0]) # 모든행에서 첫번째열을 선택하라
print(A[A[:,0]<0, :]) # 0번째 의 열이 음수인것들을 가지고 온다


# 1. A[:,0]<0, : --> 모든 행의 첫번째 열이 0보다 작은지를 판별
# 2. []는 boolean 을 의미, 참,거짓으로 판별 --> ture 인 경우만 배출

[[ 1.2995202   0.76579096 -0.86512944]
 [-0.64755505 -0.98459926  1.79854237]
 [ 0.83285696 -0.36329001  0.40869042]]
[[0.72719356 0.93950782 0.22608037]
 [0.39409431 0.74945208 0.89007475]
 [0.20154865 0.19027563 0.14168018]]
[ 1.2995202  -0.64755505  0.83285696]
[[-0.64755505 -0.98459926  1.79854237]]


In [ ]:
A = np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))

print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) # np.exp(1) =  e의 1 승의 log 니까 1
print(np.log(10))

print(np.round(A, 2)) # 특정 자리 수까지 반올림


[[ 0.52068183 -0.51763082 -0.26824867]
 [-1.10476724 -0.14239701  0.26304086]
 [ 0.2681011   1.56733355 -0.10837187]]
[[0.52068183 0.51763082 0.26824867]
 [1.10476724 0.14239701 0.26304086]
 [0.2681011  1.56733355 0.10837187]]
[[0.72158286 0.71946565 0.51792728]
 [1.05107908 0.37735528 0.51287509]
 [0.5177848  1.25193193 0.32919883]]
[[1.6831749  0.59593074 0.76471759]
 [0.33128798 0.86727687 1.30087987]
 [1.30747931 4.7938486  0.89729386]]
[[-0.65261611 -0.65849299 -1.31584085]
 [ 0.09963467 -1.9491363  -1.3354459 ]
 [-1.31639114  0.4493758  -2.22218671]]
1.0
2.302585092994046
[[ 0.52 -0.52 -0.27]
 [-1.1  -0.14  0.26]
 [ 0.27  1.57 -0.11]]


In [ ]:
print(np.sin(np.pi/6))
# 최대 기울기 : 1

print(np.tanh(-10))

np.nan

np.isnan([1,2,3,4, np.nan]) # np.nan 인 경우 True를 반환

print(np.isinf([1,2,3,4,np.inf]))

# 특정 부분에서 분포를 알기 위한 것들을 알 수 있음


0.49999999999999994
-0.9999999958776927
[False False False False  True]


In [ ]:
A=np.random.randn(3,4)
print(A)

print(np.max(A))

print(np.max(A, axis=0)) # 각 열의 최댓값을 뽑아서 나열(세로로)

print(np.max(A, axis=1)) # 각 행에 대해서 최댓값을 뽑아서 나열(가로로)

print(np.max(A, axis=0, keepdims  = True )), # 차원을 그대로 유지해주면서 출력

print(np.argmax(A)) # 가장 큰 숫자가 있는 인덱스를 출력 arg + max --> 가로로 읽기





[[-0.20140013 -0.36160283  0.8576644   1.38378123]
 [ 0.60521294  1.9680552  -0.5314809   0.48464126]
 [-0.45759416  0.09357689 -0.42007454  1.38676   ]]
1.9680552029528275
[0.60521294 1.9680552  0.8576644  1.38676   ]
[1.38378123 1.9680552  1.38676   ]
[[0.60521294 1.9680552  0.8576644  1.38676   ]]
5


In [ ]:
a=np.random.randn(6,1)

print(a)

a_sorted = np.sort(a)
print(a_sorted)

print(np.flipud(a_sorted)) # np.flipud 내림차순 가능




[[-0.39282336]
 [ 1.24363241]
 [-0.67692   ]
 [ 0.53978567]
 [ 0.07356449]
 [-0.09888866]]
[[-0.39282336]
 [ 1.24363241]
 [-0.67692   ]
 [ 0.53978567]
 [ 0.07356449]
 [-0.09888866]]
[[-0.09888866]
 [ 0.07356449]
 [ 0.53978567]
 [-0.67692   ]
 [ 1.24363241]
 [-0.39282336]]


In [ ]:
A = np.random.randn(3,4)
print(A)

print(np.sum(A))
print(np.sum(A, axis=1)) # 가로로 모든 값을 더한다
print(np.sum(A, axis=1, keepdims = True)) # 3행 1열을 유지

print(np.mean(A, axis=1, keepdims = True)) # mean : 평균을 구하자

print(np.std(A)) # standard deviatoin 표준편차

[[ 0.88195871  0.64390163  0.0730533   1.46887852]
 [-0.45640438 -0.10987986  0.25501854 -0.20718727]
 [-0.5955544  -0.25059206  0.8328391   0.44812525]]
2.9841570578196572
[ 3.06779216 -0.51845298  0.43481789]
[[ 3.06779216]
 [-0.51845298]
 [ 0.43481789]]
[[ 0.76694804]
 [-0.12961325]
 [ 0.10870447]]
0.5953682419694021


In [ ]:
A=np.random.randint(1,5, size=(12, 1))
#randint = random + int , 사이즈가 12인 1이상 5미만 정수를 랜덤으로 주세요
# 사이즈에 따라 차원 조절 가능 , 12행 1열
print(A)
print(A.shape)

B= A.reshape(2,2,3) # 3차원(2개), 2차원(2개), 1차원(1개)
# 2행 3열자리가 2개 있다. --> reshape (차원 변경)
print(B)
print(B.ndim) #3차원 행렬이다

[[3]
 [3]
 [1]
 [1]
 [2]
 [1]
 [4]
 [1]
 [2]
 [3]
 [4]
 [4]]
(12, 1)
[[[3 3 1]
  [1 2 1]]

 [[4 1 2]
  [3 4 4]]]
3


In [ ]:
# 내적을 하라(2+4+3= 9)
a=np.array([1,2,3])
b=np. array([2,2,1])


print(np.sum(a*b))

a=a.reshape(3,1) # 열벡터로 변환
b=b.reshape(3,1)

print(a.transpose()@b) # @: 찐 행렬 곱셈
print(a.T@b) # transpse --> T

A= np.random.randn(4,3,2)
print(A.transpose(0,1,2).shape) # 인덱스 에 맞추어서 재정렬 가능

9
[[9]]
[[9]]
(4, 3, 2)


In [ ]:
A=np.arange(20) # arange: 시작, 끝, 스텝 순으로 연속된 배열의 숫자를 생성한다
print(A)
print(A.reshape(4,5)) # 4행 5열의 배열을 완성시킨다


print(A.reshape(4,-1)) # 4개의 행이 되도록 열을 알아서 알려줘
print(A.reshape(2,5,-1)) # 알아서 만들어줌

#-1을 사용하면 알아서 차원으로 만들어준다, 1자리만 알아서

print(A.reshape(-1, 1).shape)






[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(20, 1)


In [ ]:
x=np.random.randn(2,3,4,5,6)

print(x[1,2,:,:,:].shape)
#5차원에서 1번쨰거, 4차원에서 2번쨰 거 나머지 all 이니까 차원은 (4,5,6)

print(x[1,2,...].shape) # ...은 이 뒤로는 다 같다라는 뜻이다

print(x[..., 3].shape)



(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)


NameError: name 'shape' is not defined

In [ ]:
a=np.ones((2,2)) #특정부분을 모두 1으로 바꾼다
b= np.zeros((2,2)) # 특정부분을 모두 0로 바꾼다
c= np.hstack([a,b]) # horizontal(가로) : 가로 방향으로 세워서 계산
d= np.vstack([a,b]) # vertical(세로) : 세로 방향으로 세워서 계산
e = np.block([a,b]) # 수평으로 결합
f= np.block([[a], [b]]) # 수직적으로 결합
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


In [ ]:
A = np.random.randn(1,1,1,3,1,1,4,1)
print(A)
# 3행 4열로 바꾸고 싶은 경우

print(A.shape)
print(A.squeeze().shape) # squeeze() 함수를 호출하여 1을 모두 제거

print(A.squeeze(axis = (0,2,4,5)).shape) # 원하는 부분의 1을 제거가능

[[[[[[[[ 0.62566931]
       [ 1.63586257]
       [ 0.20026717]
       [ 0.79655695]]]]



    [[[[ 1.25621536]
       [ 1.146388  ]
       [-0.4108596 ]
       [-0.42021407]]]]



    [[[[ 0.17074452]
       [ 0.66118824]
       [-0.46094039]
       [ 1.56230217]]]]]]]]
(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [ ]:
A=np.random.randn(3,4)
A1= A[np.newaxis, ...] # 첫번째에 새로운 차원을 추가하고 나머지는 유지(...)
# np.newaxis is None : True

A2= A[None, ...]
print(A2.shape)
print(A1.shape) # 앞에 1이 추가됨

A3 = A[..., None]
print(A3.shape)


A4 = A[:, None, :]
print(A4.shape) # 중간삽입도 가능


A5 = np.expand_dims(A, axis=1) # 인덱스 1자리에 차원을 추가: 지점을 지정할 수 있음
print(A5.shape)

(1, 3, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(3, 1, 4)


In [ ]:
np.newaxis is None

True